isawnyu/PleiadesEntity

browser/attestations.py
skins/PleiadesEntity/place_map.js
skins/PleiadesEntity/place_view.pt

Place page content is flowed around map. Closes #7

Issue7 implemented

---

Products/PleiadesEntity/browser/attestations.py
Products/PleiadesEntity/browser/configure.zcml
Products/PleiadesEntity/skins/PleiadesEntity/place_view.pt

I am quite confused as to why parts of place_view.pt related to connectionsField are showing up in this PR. I know that is work @alecpm did, which I thought was already in staging.

Representative point

---

Products/PleiadesEntity/browser/adapters/place.py
Products/PleiadesEntity/browser/attestations.py
Products/PleiadesEntity/browser/configure.zcml
Products/PleiadesEntity/config.py
Products/PleiadesEntity/content/Connection.py
Products/PleiadesEntity/content/Named.py
Products/PleiadesEntity/content/Place.py
Products/PleiadesEntity/content/__init__.py
Products/PleiadesEntity/content/interfaces.py
Products/PleiadesEntity/profiles.zcml
Products/PleiadesEntity/profiles/default/diff_tool.xml
Products/PleiadesEntity/profiles/default/factorytool.xml
Products/PleiadesEntity/profiles/default/metadata.xml
Products/PleiadesEntity/profiles/default/types.xml
Products/PleiadesEntity/profiles/default/types/Connection.xml
Products/PleiadesEntity/setuphandlers.py
Products/PleiadesEntity/skins/PleiadesEntity/place_view.pt

Implements stories 41, 42, 43, 45, 46. I made this pull request to master because there are additional commits on master not on staging that make the diffs overly complex. Also, it's not clear to me if those changes are changes we want on staging.

Add connection content type for new connections

---

Products/PleiadesEntity/content/ReferenceCitation.py
Products/PleiadesEntity/content/Work.py

Fixes https://github.com/isawnyu/pleiades-gazetteer/issues/324

address usability problems for references in edit forms

---

Products/PleiadesEntity/browser/attestations.py

Also regularize and economize description of languages and periods. Addresses https://github.com/isawnyu/pleiades-gazetteer/issues/23

better surface association certainty for names and locations

---

Products/PleiadesEntity/browser/attestations.py

Addresses https://github.com/isawnyu/pleiades-gazetteer/issues/329

ensure all string components are unicode in connections listing

---

Products/PleiadesEntity/browser/attestations.py

Addresses https://github.com/isawnyu/pleiades-gazetteer/issues/328

create connections listings more robustly

---

Products/PleiadesEntity/skins/PleiadesEntity/map_icons/reset-box.svg
Products/PleiadesEntity/skins/PleiadesEntity/place_map.js
Products/PleiadesEntity/skins/PleiadesEntity/place_view.pt
Products/PleiadesEntity/skins/PleiadesEntity/reset-box.svg

Addresses https://github.com/isawnyu/pleiades-gazetteer/issues/406

Issue406: migrate place maps to mapboxgl

---

Products/PleiadesEntity/skins/PleiadesEntity/place_map.js

addresses https://github.com/isawnyu/pleiades-gazetteer/issues/406

use mapboxgl for place maps

---

Products/PleiadesEntity/skins/PleiadesEntity/location_map.js

addressing https://github.com/isawnyu/pleiades-gazetteer/issues/420

rotated mapbox access tokens for location maps

---

Products/PleiadesEntity/browser/credits.py

addresses https://github.com/isawnyu/pleiades-gazetteer/issues/442

make history concatenation on workflow transition and check-in unicode safe

---

Products/PleiadesEntity/skins/PleiadesEntity/place_map.js
Products/PleiadesEntity/skins/PleiadesEntity/place_view.pt

Construct cache-busting URIs for JSON resources when authenticated. Fixes https://github.com/isawnyu/pleiades-gazetteer/issues/444

make place maps update during editing

---

Products/PleiadesEntity/browser/attestations.py

Fixes https://github.com/isawnyu/pleiades-gazetteer/issues/161

subdivide names listing by type

---

Products/PleiadesEntity/browser/osm.py

See https://github.com/isawnyu/pleiades-gazetteer/issues/414
﻿

Increment a suffix until we find a suitable id

---

Products/PleiadesEntity/skins/PleiadesEntity/forms.js

See https://github.com/isawnyu/pleiades-gazetteer/issues/468

Do not overwrite 'Access URI' if already present when fetchinf from Zotero

---

Products/PleiadesEntity/skins/PleiadesEntity/place_map.js

See isawnyu/pleiades-gazetteer#481

Update JS to render other geometries

---

Products/PleiadesEntity/browser/osm.py

See https://github.com/isawnyu/pleiades-gazetteer/issues/482

Fix OSM relation import

---

Products/PleiadesEntity/browser/adapters/__init__.py

Related to https://github.com/isawnyu/pleiades-gazetteer/issues/463

Include normal workflow event in JSON history

---

Products/PleiadesEntity/browser/adapters/__init__.py

Addresses [#495](https://github.com/isawnyu/pleiades-gazetteer/issues/495)
This might not be the best way to achieve the required disambiguation.

dict_getter needs to add different methods for same key if prefix is different

---

Products/PleiadesEntity/browser/configure.zcml
Products/PleiadesEntity/browser/references.py
Products/PleiadesEntity/browser/viewlets.py
Products/PleiadesEntity/content/ReferenceCitation.py
Products/PleiadesEntity/profiles.zcml
Products/PleiadesEntity/profiles/default/cssregistry.xml
Products/PleiadesEntity/profiles/default/jsregistry.xml
Products/PleiadesEntity/profiles/default/metadata.xml
Products/PleiadesEntity/skins/PleiadesEntity/forms.js
Products/PleiadesEntity/skins/PleiadesEntity/jquery.autocomplete.css
Products/PleiadesEntity/skins/PleiadesEntity/jquery.autocomplete.js
Products/PleiadesEntity/skins/PleiadesEntity/short_title_widget.pt

See https://github.com/isawnyu/pleiades-gazetteer/issues/490

Add work lookup and automcomplete widget to reference fields

---

Products/PleiadesEntity/browser/configure.zcml
Products/PleiadesEntity/content/interfaces.py
Products/PleiadesEntity/skins/PleiadesEntity/forms.js

See https://github.com/isawnyu/pleiades-gazetteer/issues/501

Fix lookup functionality for names, locations and connections

---

Products/PleiadesEntity/browser/attestations.py

See https://github.com/isawnyu/pleiades-gazetteer/issues/507

Include accuracy info in locations listing
